const assert=require('node:assert/strict');
const P=require('./puzzle.js');
const solved=P.solvedBoard();
assert.equal(P.canMove(solved,3),true);
assert.equal(P.canMove(solved,4),true);
assert.equal(P.canMove(solved,2),false);
assert.strictEqual(P.move(solved,2),solved);
const oneMove=P.move(solved,4);
assert.deepEqual(oneMove.slice(-2),[5,4]);
assert.equal(P.isSolved(solved),true);
assert.equal(P.isSolved(oneMove),false);
const shuffled=P.shuffle(()=>0.37,30);
assert.equal(P.isSolved(shuffled),false);
assert.equal(P.isSolvable(shuffled),true);
console.log('PASS: Puzzle logic QA');
